# This block is generated by rwssl to avoid renewal and
# initial acme validation errors due to .htaccess rules

location ^~ /.well-known/acme-challenge/ {
    default_type "text/plain";
    rewrite /.well-known/acme-challenge/(.*) /$1 break;
    root /var/.rwssl/.well-known/acme-challenge/;
}