############################################################################### 
# This conf file was auto-generated by rwssl script
# Author: Rehmat Alam
# GitHub Repo: (https://github.com/rehmatworks/serverpilot-letsencrypt/)
# Twitter: https://twitter.com/rehmatworks
# Email: contact@rehmat.works
###############################################################################

location / {
    proxy_pass      $backend_protocol://$backend_host:$backend_port;
}